version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci_cd_docker_django_container
    ports:
      - "9020:9020"
    volumes:
      - .:/ci_cd_docker_django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9020"
    networks:
      - mysql-network


networks:
  mysql-network:
    external:
      name: mysql-network