name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Coverage report
      runs:
        using: 'docker'
        container_name: 'ci_cd_docker_django_container'
        run:
          pip install coverage
          coverage run manage.py test
          coverage report
    - name: Django Testing
      run: |
        python3 manage.py test
